import 'dart:io';
import 'package:test/test.dart';
import '../bin/i18n/i18n_config.dart';
import '../bin/i18n/i18n_generator.dart';

void main() {
  group('Blogger Theme Internationalization (i18n) Tests', () {
    test('I18nConfig values configuration is defined correctly', () {
      expect(I18nConfig.defaultLocale, equals('en'));
      expect(I18nConfig.fallbackLocale, equals('en'));
      expect(I18nConfig.defaultCurrency, equals('INR'));
      expect(I18nConfig.fallbackCurrency, equals('INR'));
      expect(I18nConfig.supportedLocales, equals(['en', 'hi', 'fr']));
      expect(I18nConfig.supportedCurrencies, equals(['INR', 'USD', 'EUR']));
      expect(I18nConfig.currencySymbols, equals({
        'INR': '₹',
        'USD': r'$',
        'EUR': '€',
      }));
    });

    test('I18n Generator parses ARB files and produces JavaScript AppI18n dictionary', () {
      final jsScript = generateI18nScript();

      // Ensure all supported locales are bundled
      expect(jsScript, contains('"en"'));
      expect(jsScript, contains('"hi"'));
      expect(jsScript, contains('"fr"'));

      // Ensure that translated keys are present
      expect(jsScript, contains('"session_settings"'));
      expect(jsScript, contains('"preferred_currency"'));
      expect(jsScript, contains('"logout_session"'));
      expect(jsScript, contains('"preferences"'));

      // Ensure specific ARB translations exist
      expect(jsScript, contains('सत्र सेटिंग्स'));
      expect(jsScript, contains('प्राथमिकताएं'));
      expect(jsScript, contains('Paramètres de session'));
      expect(jsScript, contains('Préférences'));

      // Ensure AppI18n object and ICU message formatter are present
      expect(jsScript, contains('window.AppI18n = {'));
      expect(jsScript, contains('formatMessage: function(msg, vars = {})'));
      expect(jsScript, contains('evaluateExpression(inner, vars)'));
      expect(jsScript, contains('Intl.PluralRules'));

      // Ensure autogenerated named/typed translation methods exist on AppI18n JS
      expect(jsScript, contains('session_settings: function(vars) {'));
      expect(jsScript, contains('preferences: function(vars) {'));
      expect(jsScript, contains('logout_session: function(vars) {'));

      // Ensure Intl formatting functions exist
      expect(jsScript, contains('formatDecimal: function(val, fractionDigits = 2)'));
      expect(jsScript, contains('formatCompact: function(val)'));
      expect(jsScript, contains('formatPercent: function(val)'));
      expect(jsScript, contains('formatScientific: function(val)'));
      expect(jsScript, contains('formatCurrency: function(val, currencyCode)'));
      expect(jsScript, contains('formatDate: function(date, options'));
      expect(jsScript, contains('formatTime: function(date, use24Hour = false)'));
      expect(jsScript, contains('formatRelativeTime: function(val, unit = \'day\')'));

      // Ensure Text Direction / RTL support exists
      expect(jsScript, contains('const rtlLocales = ['));
      expect(jsScript, contains('document.documentElement.setAttribute(\'dir\', \'rtl\')'));

      // Ensure Dart Flutter-style AppI18n class is generated
      final dartI18nFile = File('bin/i18n/app_internationalization.dart');
      expect(dartI18nFile.existsSync(), isTrue);
      final dartContent = dartI18nFile.readAsStringSync();
      expect(dartContent, contains('class I18nText extends Component'));
      expect(dartContent, contains('class AppI18n'));
      expect(dartContent, contains('String get session_settings'));
      expect(dartContent, contains('Component get session_settingsComponent'));
      expect(dartContent, contains('String get preferences'));
      expect(dartContent, contains('Component get preferencesComponent'));
    });
  });
}
