import 'package:test/test.dart';
import '../bin/locales/config.dart';
import '../bin/locales/l10n_generator.dart';

void main() {
  group('Blogger Theme Internationalization Tests', () {
    test('Default values configuration is defined correctly', () {
      expect(L10nConfig.defaultLocale, equals('en'));
      expect(L10nConfig.fallbackLocale, equals('en'));
      expect(L10nConfig.defaultCurrency, equals('INR'));
      expect(L10nConfig.fallbackCurrency, equals('INR'));
      expect(L10nConfig.supportedLocales, equals(['en', 'hi', 'fr']));
      expect(L10nConfig.supportedCurrencies, equals(['INR', 'USD', 'EUR']));
      expect(L10nConfig.currencySymbols, equals({
        'INR': '₹',
        'USD': r'$',
        'EUR': '€',
      }));
    });

    test('L10n Generator parses ARB files and produces JavaScript AppLocalizations dictionary', () {
      final jsScript = generateL10nScript();

      // Ensure all supported locales are bundled
      expect(jsScript, contains('"en"'));
      expect(jsScript, contains('"hi"'));
      expect(jsScript, contains('"fr"'));

      // Ensure that translated keys are present
      expect(jsScript, contains('"session_settings"'));
      expect(jsScript, contains('"preferred_currency"'));
      expect(jsScript, contains('"logout_session"'));
      expect(jsScript, contains('"preferences"'));

      // Ensure specific ARB translations exist
      expect(jsScript, contains('सत्र सेटिंग्स')); // Hindi translation for session_settings
      expect(jsScript, contains('प्राथमिकताएं')); // Hindi translation for preferences
      expect(jsScript, contains('Paramètres de session')); // French translation for session_settings
      expect(jsScript, contains('Préférences')); // French translation for preferences

      // Ensure AppLocalizations object and ICU message formatter are present
      expect(jsScript, contains('window.AppLocalizations = {'));
      expect(jsScript, contains('formatMessage: function(msg, vars = {})'));
      expect(jsScript, contains('evaluateExpression(inner, vars)'));
      expect(jsScript, contains('Intl.PluralRules'));

      // Ensure autogenerated named/typed translation methods exist
      expect(jsScript, contains('session_settings: function(vars) {'));
      expect(jsScript, contains('preferences: function(vars) {'));
      expect(jsScript, contains('logout_session: function(vars) {'));

      // Ensure Intl formatting functions exist
      expect(jsScript, contains('formatDecimal: function(val, fractionDigits = 2)'));
      expect(jsScript, contains('formatCompact: function(val)'));
      expect(jsScript, contains('formatPercent: function(val)'));
      expect(jsScript, contains('formatScientific: function(val)'));
      expect(jsScript, contains('formatCurrency: function(val, currencyCode)'));
      expect(jsScript, contains('formatDate: function(date, options'));
      expect(jsScript, contains('formatTime: function(date, use24Hour = false)'));
      expect(jsScript, contains('formatRelativeTime: function(val, unit = \'day\')'));

      // Ensure Text Direction / RTL support exists
      expect(jsScript, contains('const rtlLocales = ['));
      expect(jsScript, contains('document.documentElement.setAttribute(\'dir\', \'rtl\')'));
    });
  });
}
